# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bssid.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'bssid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ssid.proto\x12\x05\x62ssid\"|\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x03\x12\x0b\n\x03lon\x18\x02 \x01(\x03\x12\x0c\n\x04hacc\x18\x03 \x01(\x05\x12\x0c\n\x04zero\x18\x04 \x01(\x05\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x05\x12\x0c\n\x04vacc\x18\x06 \x01(\x05\x12\x0c\n\x04unk1\x18\x07 \x01(\x05\x12\x0c\n\x04unk2\x18\x08 \x01(\x05\"M\n\x08\x42SSIDGeo\x12\r\n\x05\x62ssid\x18\x01 \x02(\t\x12!\n\x08location\x18\x02 \x01(\x0b\x32\x0f.bssid.Location\x12\x0f\n\x07\x63hannel\x18\x15 \x01(\x05\"k\n\x0cWiFiLocation\x12\x0c\n\x04unk1\x18\x01 \x01(\x03\x12\x1d\n\x04wifi\x18\x02 \x03(\x0b\x32\x0f.bssid.BSSIDGeo\x12\r\n\x05noise\x18\x03 \x01(\x05\x12\x0e\n\x06single\x18\x04 \x01(\x05\x12\x0f\n\x07\x41PIName\x18\x05 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bssid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATION']._serialized_start=22
  _globals['_LOCATION']._serialized_end=146
  _globals['_BSSIDGEO']._serialized_start=148
  _globals['_BSSIDGEO']._serialized_end=225
  _globals['_WIFILOCATION']._serialized_start=227
  _globals['_WIFILOCATION']._serialized_end=334
# @@protoc_insertion_point(module_scope)
