# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bssid.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ssid.proto\"|\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x03\x12\x0b\n\x03lon\x18\x02 \x01(\x03\x12\x0c\n\x04hacc\x18\x03 \x01(\x05\x12\x0c\n\x04zero\x18\x04 \x01(\x05\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x05\x12\x0c\n\x04vacc\x18\x06 \x01(\x05\x12\x0c\n\x04unk1\x18\x07 \x01(\x05\x12\x0c\n\x04unk2\x18\x08 \x01(\x05\"G\n\x08\x42SSIDGeo\x12\r\n\x05\x62ssid\x18\x01 \x02(\t\x12\x1b\n\x08location\x18\x02 \x01(\x0b\x32\t.Location\x12\x0f\n\x07\x63hannel\x18\x15 \x01(\x05\"e\n\x0cWiFiLocation\x12\x0c\n\x04unk1\x18\x01 \x01(\x03\x12\x17\n\x04wifi\x18\x02 \x03(\x0b\x32\t.BSSIDGeo\x12\r\n\x05noise\x18\x03 \x01(\x05\x12\x0e\n\x06single\x18\x04 \x01(\x05\x12\x0f\n\x07\x41PIName\x18\x05 \x01(\tB2Z0github.com/gigaryte/apple-bssid-enumerator/proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bssid_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/gigaryte/apple-bssid-enumerator/proto'
  _globals['_LOCATION']._serialized_start=15
  _globals['_LOCATION']._serialized_end=139
  _globals['_BSSIDGEO']._serialized_start=141
  _globals['_BSSIDGEO']._serialized_end=212
  _globals['_WIFILOCATION']._serialized_start=214
  _globals['_WIFILOCATION']._serialized_end=315
# @@protoc_insertion_point(module_scope)
